title: <span style="font-variant:small-caps;"><font size="6.5em">Myong Jong(MJ) Shin</font></span>
logo: /profile.jpg
theme: jekyll-theme-minimal
minimal_mistakes_skin: "air"
author:
  mail: myonshin@iu.edu
  github: myonshin
